INSERT INTO menaces (id, lib, categorie, axe)
VALUES ('d0000000-0000-4000-8000-000000000002', 'MVE', 'Biologie', 'Rapide');

-- ---------------------------------------------------------------------
-- 2) Piliers rattaches a la menace MVE
-- ---------------------------------------------------------------------
-- Pilier 1 [T] : 21 exigences
INSERT INTO piliers (id, lib, menace_id)
VALUES ('e1000000-0000-4000-8000-000000000001', 'Module T - Exigences transversales de préparation applicables à tous les niveaux', 'd0000000-0000-4000-8000-000000000002');

-- Pilier 2 [C] : 12 exigences
INSERT INTO piliers (id, lib, menace_id)
VALUES ('e1000000-0000-4000-8000-000000000002', 'Module C – Communauté / Aire de Santé / IT / RECO', 'd0000000-0000-4000-8000-000000000002');

-- Pilier 3 [F] : 22 exigences
INSERT INTO piliers (id, lib, menace_id)
VALUES ('e1000000-0000-4000-8000-000000000003', 'Module F – ESS / Centre de santé', 'd0000000-0000-4000-8000-000000000002');

-- Pilier 4 [B] : 22 exigences
INSERT INTO piliers (id, lib, menace_id)
VALUES ('e1000000-0000-4000-8000-000000000004', 'Module B – BCZS : Analyse et pilotage de la surveillance', 'd0000000-0000-4000-8000-000000000002');

-- Pilier 5 [D] : 20 exigences
INSERT INTO piliers (id, lib, menace_id)
VALUES ('e1000000-0000-4000-8000-000000000005', 'Module D – DPS : Analyse et pilotage provincial', 'd0000000-0000-4000-8000-000000000002');

-- Pilier 6 [P] : 8 exigences
INSERT INTO piliers (id, lib, menace_id)
VALUES ('e1000000-0000-4000-8000-000000000006', 'Module P – Points d’Entrée / Points de Contrôle', 'd0000000-0000-4000-8000-000000000002');

-- Pilier 7 [DSE] : 20 exigences
INSERT INTO piliers (id, lib, menace_id)
VALUES ('e1000000-0000-4000-8000-000000000007', 'Module DSE – Direction Nationale de Surveillance Épidémiologique', 'd0000000-0000-4000-8000-000000000002');

-- ---------------------------------------------------------------------
-- 3) Exigences (correspondance automatique des pilier_id)
-- ---------------------------------------------------------------------
-- Exigences du pilier [T]
INSERT INTO exigences (id, lib, description, pilier_id) VALUES
('T1', 'Définition harmonisée de l’alerte — Le niveau évalué doit reconnaître clairement à quel moment le scénario devient une alerte MVE/FHV, selon une définition harmonisée et comprise de façon identique entre DSE, DPS, ZS/BCZS, CS/ESS, PoE et RECO.', 'Niveau : Minimal — Preuves attendues : Définition nationale validée, fiche de cas suspect, affiches/outils harmonisés, supports de formation ou supervision montrant la même définition aux différents niveaux.', 'e1000000-0000-4000-8000-000000000001'),
('T2', 'Détection et données minimales — Le niveau évalué doit identifier le premier détecteur du signal et garantir la collecte des informations minimales : personne, lieu, temps, symptômes, date de début, voyage ou exposition, et contact du déclarant.', 'Niveau : Minimal — Preuves attendues : Fiche d’alerte ou registre rempli avec données minimales complètes, identité du déclarant, source de détection et informations personne-lieu-temps-exposition.', 'e1000000-0000-4000-8000-000000000001'),
('T3', 'Notification immédiate — Le niveau évalué doit disposer d’un premier canal de notification et d’un canal de secours fonctionnels pour notifier immédiatement toute alerte MVE/FHV.', 'Niveau : Minimal — Preuves attendues : Registre d’appels, messages WhatsApp/SMS, notification EWARS, liste de contacts d’astreinte et preuve du canal principal plus canal de secours.', 'e1000000-0000-4000-8000-000000000001'),
('T5', 'Vérification et classification — Le niveau évalué doit identifier qui vérifie l’alerte et selon quels critères en appliquant un processus standardisé de vérification permettant de classer l’alerte comme suspecte, non suspecte, insuffisamment documentée ou à suivre.', 'Niveau : Minimal — Preuves attendues : Fiche de vérification complétée, SOP de vérification, décision de classification documentée, nom/fonction du vérificateur et critères appliqués.', 'e1000000-0000-4000-8000-000000000001'),
('T6', 'Activation de l’EIR/RRT — Le niveau évalué doit connaître qui décide l’activation de l’EIR/RRT, selon quel seuil décisionnel clair et comment cette activation est assurée en dehors des heures ouvrables.', 'Niveau : Minimal — Preuves attendues : SOP EIR, SOP d’activation, liste EIR/RRT, registre d’activation, message ou note de déploiement, preuve d’astreinte et seuil décisionnel appliqué.', 'e1000000-0000-4000-8000-000000000001'),
('T7', 'Isolement précoce du cas suspect — Le niveau évalué doit démontrer où et comment le patient suspect est séparé ou isolé rapidement en attendant l’investigation afin de limiter les expositions secondaires avant l’investigation ou le transfert.', 'Niveau : Minimal — Preuves attendues : Observation directe de l’espace d’isolement, circuit patient affiché, registre de triage, fiche d’isolement, disponibilité d’EPI et procédure de séparation.', 'e1000000-0000-4000-8000-000000000001'),
('T8', 'Circuit prélèvement-laboratoire — Le niveau évalué doit connaître le circuit de prélèvement (simple et rapide) et organise le prélèvement, le triple emballage et le transport vers le laboratoire désigné, avec responsabilités et contacts clairement établis.', 'Niveau : Minimal — Preuves attendues : Liste préleveurs, kits, triple emballage, chaîne de possession, contacts INRB/labo. SOP prélèvement-transport, fiche de demande laboratoire, registre d’échantillons, preuve du triple emballage, bordereau d’expédition et contacts du laboratoire désigné.', 'e1000000-0000-4000-8000-000000000001'),
('T9', 'Retour des résultats — Le niveau évalué doit garantir le retour opérationnel du résultat vers les niveaux concernés (ESS, BCZS, DPS, DSE) et vers la famille, sans rupture d’information après le prélèvement.', 'Niveau : Minimal — Preuves attendues : Résultat laboratoire transmis, registre de communication des résultats, message de feedback, accusé de réception et preuve de notification vers les niveaux concernés.', 'e1000000-0000-4000-8000-000000000001'),
('T10', 'Listing précoce des contacts — Le niveau évalué doit identifier qui commence le listing initial des contacts dès forte suspicion, sans attendre la confirmation biologique, et assurer la consolidation progressive des listes.', 'Niveau : Minimal — Preuves attendues : Liste initiale des contacts horodatée, liste agents/patients/accompagnants exposés, fiche d’investigation, registre de contact tracing, mise à jour progressive et responsable désigné du listing.', 'e1000000-0000-4000-8000-000000000001'),
('T11', 'Gestion des rumeurs communautaires — Le niveau évalué est en mesure de capter, documenter et transmettre les rumeurs, refus et inquiétudes communautaires en les intégrant à la surveillance et aux activités RCCE-CBS-surveillance.', 'Niveau : Minimal — Preuves attendues : Registre des rumeurs, fiche de signal communautaire, feedback communautaire, CR réunions RCCE/surveillance, preuve de transmission au niveau supérieur et actions de réponse aux rumeurs.', 'e1000000-0000-4000-8000-000000000001'),
('T12', 'Cohérence inter-niveaux — Le niveau évalué doit démontrer que la même alerte est visible, comprise et documentée de manière cohérente entre RECO, CS/ESS, BCZS, DPS et DSE, sans circuit parallèle non réconcilié.', 'Niveau : Minimal — Preuves attendues : Comparaison concordante des registres RECO/FOSA/BCZS/DPS/DSE, identifiant unique ou description identique de l’alerte, rapports alignés et écarts réconciliés.', 'e1000000-0000-4000-8000-000000000001'),
('T13', 'Gestion des 24 premières heures — Le niveau évalué doit pouvoir décrire précisément, étape par étape, ce qui se passe pendant les premières 24 heures après l’identification du cas suspect, depuis la communauté jusqu’au niveau central.', 'Niveau : Supplémentaire — Preuves attendues : Chronologie des 24 premières heures, entretien concordant avec les acteurs clés, fiches horodatées, messages de notification et décisions opérationnelles documentées.', 'e1000000-0000-4000-8000-000000000001'),
('T14', 'Surveillance 24h/24 et 7j/7 — Le niveau évalué doit démontrer la continuité de la surveillance 24h/24 et 7j/7, y compris la nuit, les week-ends et jours fériés, avec une astreinte ou un mécanisme de remplacement fonctionnel.', 'Niveau : Supplémentaire — Preuves attendues : Planning d’astreinte, liste de contacts actualisée, preuve de remplacement, journal des appels hors heures ouvrables et test de joignabilité documenté.', 'e1000000-0000-4000-8000-000000000001'),
('T15', 'Sources non conventionnelles — Le niveau évalué doit intégrer les sources non conventionnelles d’alerte, notamment ESS privés, pharmacies, tradipraticiens, marchés, transporteurs, PoE/PoC et sites de mobilité.', 'Niveau : Supplémentaire — Preuves attendues : Cartographie des sources, liste des points focaux, registre des alertes provenant de sources non conventionnelles, preuves de sensibilisation ou comptes rendus de réunions.', 'e1000000-0000-4000-8000-000000000001'),
('T16', 'Identification des expositions — Le niveau évalué doit identifier rapidement les expositions familiales, communautaires, nosocomiales et liées à la mobilité, incluant les accompagnants, transporteurs, agents de santé et co-voyageurs.', 'Niveau : Supplémentaire — Preuves attendues : Fiche d’investigation avec histoire d’exposition, liste des lieux visités, liste des personnes exposées, cartographie des contacts et données de mobilité.', 'e1000000-0000-4000-8000-000000000001'),
('T17', 'Suivi des décisions opérationnelles — Le niveau évalué doit documenter les décisions prises après vérification de l’alerte et assurer leur suivi : isolement, investigation, prélèvement, transfert, contact listing, communication ou supervision.', 'Niveau : Supplémentaire — Preuves attendues : Compte rendu de décision, registre de suivi des actions, matrice décisions-actions-responsables-délais, rapport de supervision ou preuve d’exécution.', 'e1000000-0000-4000-8000-000000000001'),
('T18', 'Analyse des retards — Le niveau évalué doit analyser les retards ou blocages observés dans la cascade de surveillance et proposer des actions correctrices documentées.', 'Niveau : Supplémentaire — Preuves attendues : Analyse des délais, tableau des goulots d’étranglement, compte rendu de revue, plan d’amélioration ou matrice gap-to-action.', 'e1000000-0000-4000-8000-000000000001'),
('T19', 'Feedback aux déclarants — Le niveau évalué doit assurer un feedback documenté vers le niveau déclarant et les acteurs impliqués, afin de maintenir la vigilance, la redevabilité et la qualité des alertes.', 'Niveau : Supplémentaire — Preuves attendues : Message ou fiche de feedback, accusé de réception, rapport de réunion, supervision documentée ou registre de retour d’information aux déclarants.', 'e1000000-0000-4000-8000-000000000001'),
('T20', 'Preuves documentaires — Le niveau évalué doit disposer de preuves vérifiables et non seulement déclaratives : registres, fiches, messages, rapports, listes de contacts, exports EWARS, comptes rendus ou observations directes.', 'Niveau : Supplémentaire — Preuves attendues : Dossier complet d’alerte comprenant registres, fiches, messages, rapports, listes de contacts, exports système et preuves d’observation directe.', 'e1000000-0000-4000-8000-000000000001'),
('T21', 'Reconstruction d’une alerte — Le niveau évalué doit être capable de reconstruire la chronologie complète d’une alerte récente ou simulée, depuis le premier signal jusqu’au feedback final.', 'Niveau : Supplémentaire — Preuves attendues : Chronogramme complet d’une alerte, dossier d’audit rétrospectif, concordance entre sources documentaires et validation par les acteurs impliqués.', 'e1000000-0000-4000-8000-000000000001'),
('T22', 'Actions correctrices documentées — Le niveau évalué doit transformer toute contradiction inter-niveaux, faille de procédure ou rupture de preuve en gap majeur documenté avec action corrective, responsable, délai et moyen de vérification.', 'Niveau : Supplémentaire — Preuves attendues : Matrice gap-to-action renseignée, responsable désigné, échéance, moyen de vérification, suivi de mise en œuvre et preuve de clôture ou de progrès.', 'e1000000-0000-4000-8000-000000000001')
ON DUPLICATE KEY UPDATE
    lib = VALUES(lib),
    description = VALUES(description),
    pilier_id = VALUES(pilier_id),
    is_deleted = FALSE,
    updated_at = utc_timestamp();

-- Exigences du pilier [C]
INSERT INTO exigences (id, lib, description, pilier_id) VALUES
('C1', 'Détection des signaux communautaires prioritaires — Les RECO et IT identifient rapidement et notifient les signaux communautaires prioritaires de MVE/FHV, notamment les décès inhabituels, fièvres avec saignements, maladies groupées, retours de zones à risque et contacts avec un malade ou un décès suspect.', 'Niveau : Minimal — Preuves attendues : Questionnement direct de 2-3 RECO/IT, fiche de signalement, affichage des signaux prioritaires.', 'e1000000-0000-4000-8000-000000000002'),
('C2', 'Enregistrement des signaux communautaires — Les signaux communautaires sont systématiquement enregistrés avec la date, l''heure, la source du signal et l''action entreprise afin d''assurer leur traçabilité.', 'Niveau : Minimal — Preuves attendues : Registre des signaux communautaires et exemples des 30 à 60 derniers jours.', 'e1000000-0000-4000-8000-000000000002'),
('C3', 'Qualité des informations collectées — Les alertes communautaires contiennent les informations minimales requises pour permettre leur vérification rapide et leur exploitation par les structures sanitaires.', 'Niveau : Minimal — Preuves attendues : Échantillon de fiches de signalement et analyse de la complétude des champs clés.', 'e1000000-0000-4000-8000-000000000002'),
('C4', 'Rapidité de notification communautaire — Les alertes détectées au niveau communautaire sont transmises immédiatement à l''IT, à la FOSA ou au BCZS dans des délais compatibles avec une réponse rapide.', 'Niveau : Minimal — Preuves attendues : Horodatage des registres, entretiens et vérification par appel test.', 'e1000000-0000-4000-8000-000000000002'),
('C5', 'Continuité du système d''alerte communautaire — La communauté dispose d''un mécanisme de remplacement lorsque le RECO ou l''IT principal est absent ou indisponible afin d''assurer la continuité de la notification.', 'Niveau : Minimal — Preuves attendues : Liste des remplaçants, test récent, disponibilité des moyens de communication.', 'e1000000-0000-4000-8000-000000000002'),
('C6', 'Rétro-information aux acteurs communautaires — Les RECO reçoivent un retour d''information après la notification d''une alerte afin de maintenir leur vigilance et renforcer la confiance dans le système de surveillance.', 'Niveau : Minimal — Preuves attendues : Exemples de feedback, messages reçus et comptes rendus de réunions communautaires.', 'e1000000-0000-4000-8000-000000000002'),
('C7', 'Représentativité du réseau communautaire — Les leaders religieux, chefs communautaires, écoles, marchés, transporteurs, pharmacies et tradipraticiens sont intégrés dans le réseau de détection précoce des alertes.', 'Niveau : Minimal — Preuves attendues : Cartographie communautaire, liste de contacts et preuves de briefing ou sensibilisation.', 'e1000000-0000-4000-8000-000000000002'),
('C8', 'Gestion sécurisée d''une alerte avant l''arrivée de la RRT — Les RECO savent appliquer les mesures de prévention appropriées avant l''arrivée de la RRT sans s''exposer ni déplacer inutilement le patient suspect.', 'Niveau : Minimal — Preuves attendues : Exercices de mise en situation, aide-mémoire et consignes communautaires.', 'e1000000-0000-4000-8000-000000000002'),
('C9', 'Contribution au listing initial des contacts — Les RECO sont capables d''identifier et de documenter rapidement les contacts communautaires potentiellement exposés avant le déploiement complet de l''équipe d''investigation.', 'Niveau : Minimal — Preuves attendues : Formulaires de listing, exemples de listes de contacts et attestations de formation.', 'e1000000-0000-4000-8000-000000000002'),
('C10', 'Surveillance des rumeurs et des refus — Les rumeurs, refus d''isolement, refus de prélèvement, refus de transfert, refus liés aux résultats ou aux enterrements sécurisés sont enregistrés et analysés.', 'Niveau : Minimal — Preuves attendues : Registre des rumeurs/feedbacks et comptes rendus d''analyse en réunion BCZS ou DPS.', 'e1000000-0000-4000-8000-000000000002'),
('C11', 'Notification des décès suspects communautaires — Les ménages et leaders communautaires connaissent les personnes ou structures à contacter avant tout enterrement d''un décès suspect.', 'Niveau : Minimal — Preuves attendues : Entretiens avec leaders communautaires, messages de sensibilisation et supports IEC diffusés.', 'e1000000-0000-4000-8000-000000000002'),
('C12', 'Utilisation des données communautaires — Les données issues de la surveillance communautaire sont consolidées par l''Aire de Santé et le BCZS et utilisées pour orienter les supervisions et interventions ciblées.', 'Niveau : Minimal — Preuves attendues : Tableau mensuel de surveillance communautaire, cartes d''alertes et plans de supervision.', 'e1000000-0000-4000-8000-000000000002')
ON DUPLICATE KEY UPDATE
    lib = VALUES(lib),
    description = VALUES(description),
    pilier_id = VALUES(pilier_id),
    is_deleted = FALSE,
    updated_at = utc_timestamp();

-- Exigences du pilier [F]
INSERT INTO exigences (id, lib, description, pilier_id) VALUES
('F1', 'L’ESS dispose d’une définition d’alerte MVE/FHV affichée et comprise par le personnel de l’accueil, du triage, des urgences et des consultations, de jour comme de nuit.', 'Niveau : Minimal — Preuves attendues : Définition nationale validée et affichée, aide-mémoire au triage, et entretien avec le personnel de jour et de nuit confirmant sa compréhension.', 'e1000000-0000-4000-8000-000000000003'),
('F2', 'L’ESS applique un triage systématique à tous les patients avant leur accès à la salle d’attente ou à la consultation afin de réduire le risque de cas manqué.', 'Niveau : Minimal — Preuves attendues : Observation directe du triage, fiche ou registre de triage rempli, procédure affichée et échantillon de dossiers montrant que tous les patients sont filtrés.', 'e1000000-0000-4000-8000-000000000003'),
('F3', 'Le triage collecte systématiquement les informations de voyage, provenance, exposition, contact avec un malade ou un décès suspect, participation à des funérailles, symptômes clés et date de début des signes.', 'Niveau : Minimal — Preuves attendues : Fiche de triage comportant les champs voyage, provenance, exposition, contact, funérailles, symptômes et date de début, avec échantillon de fiches complètes.', 'e1000000-0000-4000-8000-000000000003'),
('F4', 'L’ESS dispose d’un registre d’alertes horodaté permettant la traçabilité complète des alertes et le suivi des délais de détection et de notification.', 'Niveau : Minimal — Preuves attendues : Registre d’alertes ou des voyageurs malades renseigné, horodatages complets, source/localisation, décision et échantillon récent permettant de reconstituer la traçabilité.', 'e1000000-0000-4000-8000-000000000003'),
('F5', 'L’ESS notifie immédiatement toute alerte MVE/FHV au BCZS par un canal de communication identifié, avec un mécanisme de secours en cas d’indisponibilité du canal principal.', 'Niveau : Minimal — Preuves attendues : Journal d’appels ou messages SMS/WhatsApp/EWARS horodatés, liste des contacts d’astreinte et test documenté du canal principal et du canal de secours.', 'e1000000-0000-4000-8000-000000000003'),
('F6', 'L’ESS connaît et applique correctement le circuit de notification vers EWARS, l’Aire de Santé ou le BCZS afin d’éviter les doubles notifications ou les omissions.', 'Niveau : Minimal — Preuves attendues : Schéma officiel du circuit de notification, procédure EWARS, registres concordants entre niveaux et exemples récents de notifications sans doublon ni omission.', 'e1000000-0000-4000-8000-000000000003'),
('F7', 'L’ESS participe à une boucle de rétro-information lui permettant de recevoir et d’utiliser le feedback du BCZS après chaque alerte ou investigation.', 'Niveau : Minimal — Preuves attendues : Messages ou bulletins de feedback, comptes rendus de réunions, liste de diffusion et exemples d’actions correctrices prises à la suite du retour reçu.', 'e1000000-0000-4000-8000-000000000003'),
('F8', 'L’ESS dispose d’un espace de séparation ou d’isolement temporaire fonctionnel permettant de réduire les expositions des patients, accompagnants et agents de santé.', 'Niveau : Minimal — Preuves attendues : Observation directe ou cartographie des espaces d’isolement, photos ou fiche de contrôle, circuit patient affiché, disponibilité d’EPI et test de fonctionnalité.', 'e1000000-0000-4000-8000-000000000003'),
('F9', 'L’ESS dispose d’un circuit clairement défini pour la prise en charge, l’isolement et le transfert sécurisé d’un cas suspect de MVE.', 'Niveau : Minimal — Preuves attendues : SOP de référence et transfert, coordonnées actualisées de la structure et de l’ambulance, fiches de référence, registre de transferts et rapport d’exercice ou de cas récent.', 'e1000000-0000-4000-8000-000000000003'),
('F10', 'L’ESS identifie, limite et enregistre les accompagnants des patients suspects afin de réduire les expositions secondaires et faciliter le contact listing.', 'Niveau : Minimal — Preuves attendues : Registre des accompagnants ou manifeste de voyageurs, liste initiale des contacts avec coordonnées et itinéraires, et preuve de transmission à l’équipe chargée du suivi.', 'e1000000-0000-4000-8000-000000000003'),
('F11', 'Le personnel de l’ESS collecte et documente les informations essentielles nécessaires à l’investigation avant l’arrivée de l’équipe d’intervention rapide.', 'Niveau : Minimal — Preuves attendues : Fiches d’alerte ou d’investigation préremplies, aide-mémoire des données minimales et échantillon de dossiers remis à l’EIR avant son arrivée.', 'e1000000-0000-4000-8000-000000000003'),
('F12', 'L’ESS est capable d’identifier rapidement les agents de santé, patients, visiteurs et accompagnants potentiellement exposés à un cas suspect.', 'Niveau : Minimal — Preuves attendues : Registre des accompagnants ou manifeste de voyageurs, liste initiale des contacts avec coordonnées et itinéraires, et preuve de transmission à l’équipe chargée du suivi.', 'e1000000-0000-4000-8000-000000000003'),
('F13', 'L’ESS dispose d’un protocole opérationnel pour la gestion et la notification d’un cas suspect de MVE, y compris dans les structures privées ou insuffisamment préparées.', 'Niveau : Minimal — Preuves attendues : Protocole validé et disponible, circuit de notification affiché, preuve de diffusion aux structures concernées et rapport de simulation ou d’application récente.', 'e1000000-0000-4000-8000-000000000003'),
('F14', 'Le personnel connaît la structure de référence et les modalités de transfert sécurisé d’un cas suspect vers une structure appropriée.', 'Niveau : Minimal — Preuves attendues : SOP de référence et transfert, coordonnées actualisées de la structure et de l’ambulance, fiches de référence, registre de transferts et rapport d’exercice ou de cas récent.', 'e1000000-0000-4000-8000-000000000003'),
('F15', 'L’ESS dispose d’une procédure de gestion des refus d’isolement, de prélèvement ou de transfert garantissant la continuité de la surveillance et de la communication des risques.', 'Niveau : Minimal — Preuves attendues : Procédure de gestion des refus, fiche de consentement ou de refus, registre des incidents, preuve de counseling et plan documenté de suivi et de communication des risques.', 'e1000000-0000-4000-8000-000000000003'),
('F16', 'L’ESS connaît les responsabilités et les contacts nécessaires pour organiser le prélèvement, la gestion et l’acheminement des échantillons vers le laboratoire désigné.', 'Niveau : Minimal — Preuves attendues : SOP de prélèvement et d’acheminement, liste actualisée des responsables et contacts, formulaire laboratoire, bordereau de transport et chaîne de traçabilité d’un échantillon test.', 'e1000000-0000-4000-8000-000000000003'),
('F17', 'L’ESS dispose ou peut accéder rapidement aux kits de prélèvement, matériels de triple emballage et formulaires requis pour l’investigation biologique d’un cas suspect.', 'Niveau : Minimal — Preuves attendues : Fiche de stock à jour, observation des kits et triples emballages non périmés, formulaires disponibles et mécanisme documenté de réapprovisionnement rapide.', 'e1000000-0000-4000-8000-000000000003'),
('F18', 'Le personnel respecte les procédures de biosécurité et ne réalise la manipulation des échantillons qu’avec les compétences, équipements et autorisations requis.', 'Niveau : Minimal — Preuves attendues : SOP de biosécurité, attestations de formation et d’autorisation, observation des pratiques, registre d’incidents et disponibilité des équipements requis.', 'e1000000-0000-4000-8000-000000000003'),
('F19', 'L’ESS dispose d’EPI en quantité suffisante et le personnel maîtrise les procédures de mise en place et de retrait des équipements de protection individuelle.', 'Niveau : Minimal — Preuves attendues : Inventaire et fiches de stock d’EPI, contrôle des dates et tailles, observation ou test pratique d’habillage-déshabillage et registre de formation du personnel.', 'e1000000-0000-4000-8000-000000000003'),
('F20', 'Les agents de soutien, notamment les nettoyeurs, gardiens, brancardiers et ambulanciers, sont intégrés aux procédures de préparation et de réponse à la MVE.', 'Niveau : Minimal — Preuves attendues : Liste des agents de soutien, feuilles de présence aux briefings, supports adaptés à leurs rôles et observation ou simulation de leurs tâches en situation d’alerte.', 'e1000000-0000-4000-8000-000000000003'),
('F21', 'Les rumeurs, refus, résistances communautaires ou autres signaux sociaux observés dans l’ESS sont documentés et transmis au BCZS pour analyse et action.', 'Niveau : Minimal — Preuves attendues : Registre des rumeurs, refus et préoccupations, fiches ou rapports RCCE, analyse périodique, preuve de transmission et actions de communication ou de surveillance mises en œuvre.', 'e1000000-0000-4000-8000-000000000003'),
('F22', 'L’ESS identifie régulièrement les facteurs susceptibles d’entraîner la non-détection ou la notification tardive d’une alerte MVE et met en œuvre des mesures correctrices documentées.', 'Niveau : Minimal — Preuves attendues : Rapport d’audit ou de comparaison des registres, liste des alertes manquées ou tardives, analyse des causes et plan d’actions correctrices avec suivi de mise en œuvre.', 'e1000000-0000-4000-8000-000000000003')
ON DUPLICATE KEY UPDATE
    lib = VALUES(lib),
    description = VALUES(description),
    pilier_id = VALUES(pilier_id),
    is_deleted = FALSE,
    updated_at = utc_timestamp();

-- Exigences du pilier [B]
INSERT INTO exigences (id, lib, description, pilier_id) VALUES
('B1', 'Représentativité des sources d''alerte — Le BCZS reçoit, enregistre et analyse les alertes provenant de l''ensemble des sources de surveillance (RECO, AS, ESS publics et privés, PoE/PoC, pharmacies et tradipraticiens) afin d''assurer une couverture complète du système.', 'Niveau : Minimal — Preuves attendues : Cartographie et liste de contacts des sources publiques, privées, communautaires et multisectorielles, registres montrant leur contribution et preuves de briefing, convention ou supervision.', 'e1000000-0000-4000-8000-000000000004'),
('B2', 'Qualité et complétude du registre d''alertes — Le BCZS maintient un registre d''alertes complet incluant la date et l''heure de réception, la source, la localisation, la classification, la vérification, la décision prise et le feedback.', 'Niveau : Minimal — Preuves attendues : Registre d’alertes ou des voyageurs malades renseigné, horodatages complets, source/localisation, décision et échantillon récent permettant de reconstituer la traçabilité.', 'e1000000-0000-4000-8000-000000000004'),
('B3', 'Vérification standardisée des alertes — Le BCZS vérifie systématiquement chaque alerte selon une procédure et des critères standardisés afin de garantir une classification cohérente et reproductible.', 'Niveau : Minimal — Preuves attendues : SOP et fiche standard de vérification, critères de classification, échantillon de fiches complétées et identité du vérificateur avec décision documentée.', 'e1000000-0000-4000-8000-000000000004'),
('B4', 'Rapidité de vérification — Le BCZS vérifie les alertes dans les délais requis et suit régulièrement la proportion d''alertes vérifiées dans les 24 heures.', 'Niveau : Minimal — Preuves attendues : Registre comportant les dates et heures clés, tableau de bord des délais, calculs d’indicateurs, analyse des écarts et plan d’amélioration suivi dans le temps.', 'e1000000-0000-4000-8000-000000000004'),
('B5', 'Continuité du reporting EWARS — Le BCZS dispose d''un gestionnaire EWARS et d''un suppléant capables d''assurer la continuité de la saisie, validation et transmission des données en toute circonstance.', 'Niveau : Minimal — Preuves attendues : Décision désignant le gestionnaire EWARS et son suppléant, profils d’accès, calendrier de permanence, rapports de transmission et test de continuité documenté.', 'e1000000-0000-4000-8000-000000000004'),
('B6', 'Détection des alertes manquées — Le BCZS compare régulièrement les données EWARS avec les registres des ESS et des Aires de Santé afin d''identifier les alertes non notifiées ou perdues.', 'Niveau : Minimal — Preuves attendues : Rapport d’audit ou de comparaison des registres, liste des alertes manquées ou tardives, analyse des causes et plan d’actions correctrices avec suivi de mise en œuvre.', 'e1000000-0000-4000-8000-000000000004'),
('B7', 'Fonctionnalité de l''EIR de la Zone de Santé — Le BCZS dispose d''une équipe d''intervention rapide multidisciplinaire formellement constituée et opérationnelle pour répondre aux alertes MVE/FHV.', 'Niveau : Minimal — Preuves attendues : Décision de constitution de l’EIR/RRT, liste multidisciplinaire et contacts, termes de référence, plan de disponibilité, inventaire du matériel et rapport d’exercice ou de déploiement.', 'e1000000-0000-4000-8000-000000000004'),
('B8', 'Astreinte de l''EIR — Le BCZS maintient un mécanisme d''astreinte permettant l''activation de l''EIR en dehors des heures ouvrables.', 'Niveau : Minimal — Preuves attendues : Planning d’astreinte actualisé, liste de contacts, journal d’appels hors heures ouvrables et test d’activation documenté avec délai de réponse.', 'e1000000-0000-4000-8000-000000000004'),
('B9', 'Rapidité d''intervention sur terrain — Le BCZS mesure et améliore le délai entre la vérification de l''alerte et l''arrivée effective de l''équipe sur le terrain.', 'Niveau : Minimal — Preuves attendues : Registre comportant les dates et heures clés, tableau de bord des délais, calculs d’indicateurs, analyse des écarts et plan d’amélioration suivi dans le temps.', 'e1000000-0000-4000-8000-000000000004'),
('B10', 'Disponibilité des moyens opérationnels — Le BCZS dispose immédiatement des moyens de transport, communication, carburant, EPI et outils nécessaires à l''investigation rapide des alertes.', 'Niveau : Minimal — Preuves attendues : Inventaire disponible et fonctionnel du transport, carburant, communication, EPI et outils; fiches de stock; bon de carburant; et contrôle ou exercice de disponibilité immédiate.', 'e1000000-0000-4000-8000-000000000004'),
('B11', 'Traçabilité des investigations — Le BCZS transmet, archive et exploite les rapports d''investigation afin d''assurer la traçabilité et l''apprentissage institutionnel.', 'Niveau : Minimal — Preuves attendues : Registre des investigations, rapports signés et archivés, accusés de transmission, base de suivi des recommandations et exemples d’exploitation lors d’une revue.', 'e1000000-0000-4000-8000-000000000004'),
('B12', 'Cartographie des capacités d''isolement — Le BCZS connaît les ESS capables d''assurer l''isolement temporaire d''un cas suspect et les utilise pour orienter rapidement les alertes.', 'Niveau : Minimal — Preuves attendues : Observation directe ou cartographie des espaces d’isolement, photos ou fiche de contrôle, circuit patient affiché, disponibilité d’EPI et test de fonctionnalité.', 'e1000000-0000-4000-8000-000000000004'),
('B13', 'Référence et transfert sécurisés — Le BCZS assure que les ESS connaissent et appliquent le circuit officiel de référence et de transport sécurisé des cas suspects.', 'Niveau : Minimal — Preuves attendues : SOP de référence et transfert, coordonnées actualisées de la structure et de l’ambulance, fiches de référence, registre de transferts et rapport d’exercice ou de cas récent.', 'e1000000-0000-4000-8000-000000000004'),
('B14', 'Circuit laboratoire fonctionnel — Le BCZS maîtrise et applique le circuit de prélèvement, triple emballage et transport des échantillons afin de réduire les délais diagnostiques.', 'Niveau : Minimal — Preuves attendues : Fiche de stock à jour, observation des kits et triples emballages non périmés, formulaires disponibles et mécanisme documenté de réapprovisionnement rapide.', 'e1000000-0000-4000-8000-000000000004'),
('B15', 'Analyse des retards diagnostiques — Le BCZS documente et analyse les retards liés au prélèvement, au transport ou aux résultats afin d''améliorer la performance du système.', 'Niveau : Minimal — Preuves attendues : Registre comportant les dates et heures clés, tableau de bord des délais, calculs d’indicateurs, analyse des écarts et plan d’amélioration suivi dans le temps.', 'e1000000-0000-4000-8000-000000000004'),
('B16', 'Analyse épidémiologique des alertes — Le BCZS produit régulièrement une analyse des alertes par personne, lieu, temps et source afin de détecter les clusters et les zones à risque.', 'Niveau : Minimal — Preuves attendues : Bulletin ou rapport d’analyse récent ventilé par personne, lieu, temps, source et étape de la cascade, graphiques ou cartes, conclusions et compte rendu de revue analytique.', 'e1000000-0000-4000-8000-000000000004'),
('B17', 'Suivi des indicateurs de la cascade d''alerte — Le BCZS suit les indicateurs clés de performance de la surveillance, depuis la réception des alertes jusqu''au suivi des contacts.', 'Niveau : Minimal — Preuves attendues : Registre comportant les dates et heures clés, tableau de bord des délais, calculs d’indicateurs, analyse des écarts et plan d’amélioration suivi dans le temps.', 'e1000000-0000-4000-8000-000000000004'),
('B18', 'Identification des zones silencieuses — Le BCZS identifie et investigue les zones ou ESS sans notification afin de détecter les angles morts du système.', 'Niveau : Minimal — Preuves attendues : Carte ou liste des zones silencieuses croisée avec le niveau de risque, données de complétude et promptitude, rapport d’analyse et preuves de relance, supervision ou investigation.', 'e1000000-0000-4000-8000-000000000004'),
('B19', 'Feedback aux acteurs de surveillance — Le BCZS fournit régulièrement un retour d''information documenté aux RECO, AS, ESS et PoE afin d''améliorer l''acceptabilité et la qualité de la surveillance.', 'Niveau : Minimal — Preuves attendues : Messages ou bulletins de feedback, comptes rendus de réunions, liste de diffusion et exemples d’actions correctrices prises à la suite du retour reçu.', 'e1000000-0000-4000-8000-000000000004'),
('B20', 'Intégration des signaux sociaux — Le BCZS analyse et intègre les rumeurs, feedbacks communautaires et autres signaux sociaux dans le système de surveillance et la prise de décision.', 'Niveau : Minimal — Preuves attendues : Messages ou bulletins de feedback, comptes rendus de réunions, liste de diffusion et exemples d’actions correctrices prises à la suite du retour reçu.', 'e1000000-0000-4000-8000-000000000004'),
('B21', 'Intégration du secteur privé — Le BCZS supervise et implique activement les ESS privées dans les activités de surveillance, de notification et de réponse.', 'Niveau : Minimal — Preuves attendues : Cartographie et liste de contacts des sources publiques, privées, communautaires et multisectorielles, registres montrant leur contribution et preuves de briefing, convention ou supervision.', 'e1000000-0000-4000-8000-000000000004'),
('B22', 'Reconstitution de la chaîne d''alerte — Le BCZS est capable de reconstruire intégralement la chronologie et la gestion d''une alerte récente afin de démontrer le fonctionnement réel du système.', 'Niveau : Minimal — Preuves attendues : Chronologie complète d’une alerte récente avec horodatage de chaque étape, entretiens croisés, pièces justificatives et rapport identifiant les goulots d’étranglement.', 'e1000000-0000-4000-8000-000000000004')
ON DUPLICATE KEY UPDATE
    lib = VALUES(lib),
    description = VALUES(description),
    pilier_id = VALUES(pilier_id),
    is_deleted = FALSE,
    updated_at = utc_timestamp();

-- Exigences du pilier [D]
INSERT INTO exigences (id, lib, description, pilier_id) VALUES
('D1', 'Tableau de bord provincial des alertes — La DPS dispose d''un tableau de bord provincial fonctionnel assurant le pilotage et la visibilité en temps réel des alertes MVE/FHV provenant des BCZS, FOSA, PoE et communautés.', 'Niveau : Minimal — Preuves attendues : Capture ou accès au tableau de bord fonctionnel, export récent des alertes, dictionnaire des indicateurs et preuve de mise à jour et d’utilisation lors d’une réunion de pilotage.', 'e1000000-0000-4000-8000-000000000005'),
('D2', 'Analyse périodique des alertes — La DPS analyse les alertes selon une fréquence définie afin de détecter précocement les clusters, les zones silencieuses et les retards dans la cascade de surveillance.', 'Niveau : Minimal — Preuves attendues : Bulletin ou rapport d’analyse récent ventilé par personne, lieu, temps, source et étape de la cascade, graphiques ou cartes, conclusions et compte rendu de revue analytique.', 'e1000000-0000-4000-8000-000000000005'),
('D3', 'Analyse intégrée des alertes — La DPS réalise une analyse épidémiologique et opérationnelle des alertes par personne, lieu, temps, source d''alerte et étape de la cascade de surveillance.', 'Niveau : Minimal — Preuves attendues : Bulletin ou rapport d’analyse récent ventilé par personne, lieu, temps, source et étape de la cascade, graphiques ou cartes, conclusions et compte rendu de revue analytique.', 'e1000000-0000-4000-8000-000000000005'),
('D4', 'Suivi des délais de la cascade d''alerte — La DPS surveille les délais de détection, notification, vérification, isolement et retour des résultats afin de mesurer la rapidité du système de surveillance.', 'Niveau : Minimal — Preuves attendues : Registre comportant les dates et heures clés, tableau de bord des délais, calculs d’indicateurs, analyse des écarts et plan d’amélioration suivi dans le temps.', 'e1000000-0000-4000-8000-000000000005'),
('D5', 'Évaluation de la qualité des alertes — La DPS évalue systématiquement la complétude, la pertinence, la valeur prédictive positive et les motifs de rejet des alertes afin d''optimiser la qualité du système.', 'Niveau : Minimal — Preuves attendues : Grille d’audit de qualité, échantillon de fiches contrôlées, rapport de complétude et de concordance, liste des doublons ou incohérences et corrections documentées.', 'e1000000-0000-4000-8000-000000000005'),
('D6', 'Identification des zones silencieuses — La DPS identifie les zones de santé silencieuses malgré un risque d''exposition ou une forte mobilité afin de détecter les lacunes du système de surveillance.', 'Niveau : Minimal — Preuves attendues : Carte ou liste des zones silencieuses croisée avec le niveau de risque, données de complétude et promptitude, rapport d’analyse et preuves de relance, supervision ou investigation.', 'e1000000-0000-4000-8000-000000000005'),
('D7', 'Intégration des sources non conventionnelles — La DPS intègre les ESS privés, pharmacies, tradipraticiens, marchés et transporteurs dans sa stratégie de surveillance afin de renforcer la représentativité du système.', 'Niveau : Minimal — Preuves attendues : Cartographie et liste de contacts des sources publiques, privées, communautaires et multisectorielles, registres montrant leur contribution et preuves de briefing, convention ou supervision.', 'e1000000-0000-4000-8000-000000000005'),
('D8', 'Contrôle de qualité des données — La DPS vérifie régulièrement la concordance entre EWARS, les registres des BCZS et les rapports EIR afin de détecter les doublons, incohérences et alertes manquées.', 'Niveau : Minimal — Preuves attendues : Rapport d’audit ou de comparaison des registres, liste des alertes manquées ou tardives, analyse des causes et plan d’actions correctrices avec suivi de mise en œuvre.', 'e1000000-0000-4000-8000-000000000005'),
('D9', 'Cellule d''analyse opérationnelle — La DPS dispose d''une cellule ou équipe d''analyse opérationnelle clairement définie garantissant une capacité analytique durable et indépendante d''un seul individu.', 'Niveau : Minimal — Preuves attendues : Note de service créant l’unité d’analyse, organigramme, termes de référence, liste du personnel et compétences, calendrier de permanence et productions analytiques récentes.', 'e1000000-0000-4000-8000-000000000005'),
('D10', 'Utilisation des données pour l''action — La DPS transforme les résultats des analyses en décisions opérationnelles concrètes telles que les supervisions, renforcements de capacités, appuis PCI, logistiques ou laboratoires.', 'Niveau : Minimal — Preuves attendues : Compte rendu de réunion reliant les analyses aux décisions, note de recommandation, plan d’actions avec responsables et délais, et preuve de suivi des décisions prises.', 'e1000000-0000-4000-8000-000000000005'),
('D11', 'Feedback aux Zones de Santé — La DPS fournit aux BCZS un feedback régulier, spécifique et documenté afin de renforcer la redevabilité et l''amélioration continue de la surveillance.', 'Niveau : Minimal — Preuves attendues : Messages ou bulletins de feedback, comptes rendus de réunions, liste de diffusion et exemples d’actions correctrices prises à la suite du retour reçu.', 'e1000000-0000-4000-8000-000000000005'),
('D12', 'Activation de la réponse provinciale — La DPS dispose d''un mécanisme permettant l''activation ou l''appui rapide de la RRT/EIR provinciale selon des seuils clairement définis.', 'Niveau : Minimal — Preuves attendues : SOP d’activation avec seuils, chaîne décisionnelle et contacts, registre ou message d’activation, ordre de déploiement et rapport d’exercice ou de réponse récente.', 'e1000000-0000-4000-8000-000000000005'),
('D13', 'Mécanisme d''alerte 24h/24 — La DPS maintient un dispositif fonctionnel assurant la réception et le traitement des alertes MVE/FHV 24 heures sur 24 et 7 jours sur 7.', 'Niveau : Minimal — Preuves attendues : Planning de permanence 24h/24 et 7j/7, liste de contacts d’astreinte, journal des alertes reçues hors heures ouvrables et test documenté de disponibilité.', 'e1000000-0000-4000-8000-000000000005'),
('D14', 'Intégration surveillance-laboratoire — La DPS maîtrise le circuit officiel de prélèvement, transport, analyse et retour des résultats en collaboration avec l''INRB ou le laboratoire désigné.', 'Niveau : Minimal — Preuves attendues : Registre comportant les dates et heures clés, tableau de bord des délais, calculs d’indicateurs, analyse des écarts et plan d’amélioration suivi dans le temps.', 'e1000000-0000-4000-8000-000000000005'),
('D15', 'Gestion des retards diagnostiques — La DPS documente et analyse les retards liés au prélèvement, au transport ou à la restitution des résultats afin d''améliorer la performance diagnostique.', 'Niveau : Minimal — Preuves attendues : Registre comportant les dates et heures clés, tableau de bord des délais, calculs d’indicateurs, analyse des écarts et plan d’amélioration suivi dans le temps.', 'e1000000-0000-4000-8000-000000000005'),
('D16', 'Coordination du suivi des contacts — La DPS consolide les données de contacts et assure le suivi des alertes suspectes, probables ou confirmées afin de garantir la continuité du contact tracing.', 'Niveau : Minimal — Preuves attendues : Base consolidée ou listes de contacts, procédures et outils de suivi, rapports quotidiens de complétude, chaîne de transmission et compte rendu de coordination entre niveaux.', 'e1000000-0000-4000-8000-000000000005'),
('D17', 'Exploitation des signaux sociaux — La DPS analyse conjointement les rumeurs, feedbacks communautaires et informations RCCE afin d''orienter les interventions de surveillance et de réponse.', 'Niveau : Minimal — Preuves attendues : Messages ou bulletins de feedback, comptes rendus de réunions, liste de diffusion et exemples d’actions correctrices prises à la suite du retour reçu.', 'e1000000-0000-4000-8000-000000000005'),
('D18', 'Cartographie des partenaires — La DPS maintient une matrice actualisée des partenaires par pilier, zone d''intervention et ressources disponibles afin d''optimiser la coordination opérationnelle.', 'Niveau : Minimal — Preuves attendues : Matrice actualisée des partenaires, zones, piliers, ressources et capacités, coordonnées des points focaux, comptes rendus de coordination et suivi des engagements.', 'e1000000-0000-4000-8000-000000000005'),
('D19', 'Partage des indicateurs avec la DSE — La DPS transmet régulièrement les indicateurs de surveillance à la DSE afin d''assurer la prise de décision nationale et la cohérence interprovinciale.', 'Niveau : Minimal — Preuves attendues : Tableau validé des indicateurs avec définitions, rapports ou bulletins périodiques, preuve de transmission et compte rendu montrant leur utilisation pour le pilotage.', 'e1000000-0000-4000-8000-000000000005'),
('D20', 'Production rapide de la connaissance de la situation — La DPS est capable de produire en moins de 30 minutes une synthèse complète d''une alerte majeure afin de soutenir la gestion de crise et la décision rapide.', 'Niveau : Minimal — Preuves attendues : Modèle de SITREP ou briefing, chronologie d’une alerte, synthèse produite en moins de 30 minutes lors d’un test ou événement, horodatage et liste de diffusion.', 'e1000000-0000-4000-8000-000000000005')
ON DUPLICATE KEY UPDATE
    lib = VALUES(lib),
    description = VALUES(description),
    pilier_id = VALUES(pilier_id),
    is_deleted = FALSE,
    updated_at = utc_timestamp();

-- Exigences du pilier [P]
INSERT INTO exigences (id, lib, description, pilier_id) VALUES
('P1', 'Détection et notification des alertes aux points de mobilité — Les agents du PoE/PoC, transporteurs et autres acteurs du site reconnaissent les signes d’alerte MVE/FHV et appliquent sans délai le circuit officiel de notification vers le BCZS et la DPS.', 'Niveau : Minimal — Preuves attendues : Journal d’appels ou messages SMS/WhatsApp/EWARS horodatés, liste des contacts d’astreinte et test documenté du canal principal et du canal de secours.', 'e1000000-0000-4000-8000-000000000006'),
('P2', 'Enregistrement des voyageurs malades et événements sanitaires — Le PoE/PoC enregistre systématiquement tout voyageur malade ou événement sanitaire avec la date, l’heure, la provenance et la destination afin de permettre le suivi et l’investigation.', 'Niveau : Minimal — Preuves attendues : Registre d’alertes ou des voyageurs malades renseigné, horodatages complets, source/localisation, décision et échantillon récent permettant de reconstituer la traçabilité.', 'e1000000-0000-4000-8000-000000000006'),
('P3', 'Surveillance des flux à risque — Le PoE/PoC identifie, documente et partage les informations sur les flux de voyageurs provenant de zones à risque ou utilisant des points de passage informels afin de prioriser les activités de surveillance.', 'Niveau : Minimal — Preuves attendues : Cartographie des flux et points de passage, registre de provenance-destination, analyse de risque actualisée, rapports de partage avec le BCZS/DPS et mesures de surveillance ciblées.', 'e1000000-0000-4000-8000-000000000006'),
('P4', 'Séparation précoce des voyageurs suspects — Le PoE/PoC dispose d’un espace de séparation temporaire permettant de limiter rapidement les contacts en cas de détection d’un voyageur suspect tout en évitant la panique.', 'Niveau : Minimal — Preuves attendues : Observation directe ou cartographie des espaces d’isolement, photos ou fiche de contrôle, circuit patient affiché, disponibilité d’EPI et test de fonctionnalité.', 'e1000000-0000-4000-8000-000000000006'),
('P5', 'Référence et transfert sécurisé — Le PoE/PoC connaît l’ESS de référence et applique une procédure opérationnelle de transfert sécurisé des voyageurs suspects vers la structure appropriée.', 'Niveau : Minimal — Preuves attendues : SOP de référence et transfert, coordonnées actualisées de la structure et de l’ambulance, fiches de référence, registre de transferts et rapport d’exercice ou de cas récent.', 'e1000000-0000-4000-8000-000000000006'),
('P6', 'Identification des contacts liés à la mobilité — Les transporteurs et gestionnaires du site contribuent à l’identification des co-voyageurs, itinéraires et personnes exposées afin de faciliter le listing initial des contacts.', 'Niveau : Minimal — Preuves attendues : Registre des accompagnants ou manifeste de voyageurs, liste initiale des contacts avec coordonnées et itinéraires, et preuve de transmission à l’équipe chargée du suivi.', 'e1000000-0000-4000-8000-000000000006'),
('P7', 'Intégration au système national de surveillance — Les alertes et informations recueillies au PoE/PoC sont transmises et intégrées dans les registres du CS, du BCZS, de la DPS et dans EWARS, sans système parallèle de notification.', 'Niveau : Minimal — Preuves attendues : Schéma officiel du circuit de notification, procédure EWARS, registres concordants entre niveaux et exemples récents de notifications sans doublon ni omission.', 'e1000000-0000-4000-8000-000000000006'),
('P8', 'Communication des risques et gestion des rumeurs — Le PoE/PoC met en œuvre des messages adaptés expliquant la séparation des voyageurs suspects, le transfert, le prélèvement et la communication des résultats sans stigmatisation ni amplification des rumeurs.', 'Niveau : Minimal — Preuves attendues : Messages de communication des risques validés et affichés, registre des rumeurs et préoccupations, preuves de briefing des agents et transporteurs, et exemples de réponses ou d’actions sans stigmatisation.', 'e1000000-0000-4000-8000-000000000006')
ON DUPLICATE KEY UPDATE
    lib = VALUES(lib),
    description = VALUES(description),
    pilier_id = VALUES(pilier_id),
    is_deleted = FALSE,
    updated_at = utc_timestamp();

-- Exigences du pilier [DSE]
INSERT INTO exigences (id, lib, description, pilier_id) VALUES
('DSE1', 'Tableau de bord national des alertes — La DSE dispose d’un tableau de bord national consolidé permettant le suivi et la visualisation en temps réel des alertes provenant des DPS, PoE, laboratoires et autres sources de surveillance.', 'Niveau : Minimal — Preuves attendues : Capture ou accès au tableau de bord fonctionnel, export récent des alertes, dictionnaire des indicateurs et preuve de mise à jour et d’utilisation lors d’une réunion de pilotage.', 'e1000000-0000-4000-8000-000000000007'),
('DSE2', 'Analyse nationale des alertes — La DSE analyse régulièrement les alertes afin de détecter les tendances, clusters, événements inhabituels et risques émergents à l’échelle nationale.', 'Niveau : Minimal — Preuves attendues : Bulletin ou rapport d’analyse récent ventilé par personne, lieu, temps, source et étape de la cascade, graphiques ou cartes, conclusions et compte rendu de revue analytique.', 'e1000000-0000-4000-8000-000000000007'),
('DSE3', 'Analyse intégrée des risques — La DSE réalise une analyse par personne, lieu, temps, source d’alerte et étape de la cascade afin de produire une connaissance nationale de la situation.', 'Niveau : Minimal — Preuves attendues : Bulletin ou rapport d’analyse récent ventilé par personne, lieu, temps, source et étape de la cascade, graphiques ou cartes, conclusions et compte rendu de revue analytique.', 'e1000000-0000-4000-8000-000000000007'),
('DSE4', 'Surveillance de la rapidité du système — La DSE surveille les délais de détection, notification, vérification, investigation, prélèvement et confirmation afin d’évaluer la performance nationale du système.', 'Niveau : Minimal — Preuves attendues : Registre comportant les dates et heures clés, tableau de bord des délais, calculs d’indicateurs, analyse des écarts et plan d’amélioration suivi dans le temps.', 'e1000000-0000-4000-8000-000000000007'),
('DSE5', 'Surveillance de la qualité des alertes — La DSE évalue la complétude, la pertinence, la valeur prédictive positive et les motifs de rejet des alertes à l’échelle nationale.', 'Niveau : Minimal — Preuves attendues : Grille d’audit de qualité, échantillon de fiches contrôlées, rapport de complétude et de concordance, liste des doublons ou incohérences et corrections documentées.', 'e1000000-0000-4000-8000-000000000007'),
('DSE6', 'Identification des zones silencieuses nationales — La DSE identifie les provinces et zones de santé silencieuses ou sous-performantes malgré leur niveau de risque.', 'Niveau : Minimal — Preuves attendues : Carte ou liste des zones silencieuses croisée avec le niveau de risque, données de complétude et promptitude, rapport d’analyse et preuves de relance, supervision ou investigation.', 'e1000000-0000-4000-8000-000000000007'),
('DSE7', 'Intégration multisectorielle de la surveillance — La DSE assure l’intégration des secteurs public, privé, communautaire, points d’entrée et autres sources non conventionnelles dans le système national de surveillance.', 'Niveau : Minimal — Preuves attendues : Cartographie et liste de contacts des sources publiques, privées, communautaires et multisectorielles, registres montrant leur contribution et preuves de briefing, convention ou supervision.', 'e1000000-0000-4000-8000-000000000007'),
('DSE8', 'Contrôle national de la qualité des données — La DSE vérifie la concordance entre les différentes bases de données et systèmes afin de détecter les doublons, incohérences et alertes manquées.', 'Niveau : Minimal — Preuves attendues : Rapport d’audit ou de comparaison des registres, liste des alertes manquées ou tardives, analyse des causes et plan d’actions correctrices avec suivi de mise en œuvre.', 'e1000000-0000-4000-8000-000000000007'),
('DSE9', 'Capacité nationale d’analyse opérationnelle — La DSE dispose d’une unité d’analyse clairement identifiée capable de produire des analyses épidémiologiques et opérationnelles en continu.', 'Niveau : Minimal — Preuves attendues : Note de service créant l’unité d’analyse, organigramme, termes de référence, liste du personnel et compétences, calendrier de permanence et productions analytiques récentes.', 'e1000000-0000-4000-8000-000000000007'),
('DSE10', 'Utilisation des données pour la décision — La DSE transforme les données de surveillance en recommandations et décisions opérationnelles pour la préparation et la réponse.', 'Niveau : Minimal — Preuves attendues : Compte rendu de réunion reliant les analyses aux décisions, note de recommandation, plan d’actions avec responsables et délais, et preuve de suivi des décisions prises.', 'e1000000-0000-4000-8000-000000000007'),
('DSE11', 'Feedback aux DPS — La DSE fournit un retour d’information régulier, documenté et spécifique aux DPS afin d’améliorer la qualité de la surveillance.', 'Niveau : Minimal — Preuves attendues : Messages ou bulletins de feedback, comptes rendus de réunions, liste de diffusion et exemples d’actions correctrices prises à la suite du retour reçu.', 'e1000000-0000-4000-8000-000000000007'),
('DSE12', 'Mobilisation de la réponse nationale — La DSE est capable d’activer ou de recommander l’activation des mécanismes nationaux de réponse selon des seuils clairement définis.', 'Niveau : Minimal — Preuves attendues : SOP d’activation avec seuils, chaîne décisionnelle et contacts, registre ou message d’activation, ordre de déploiement et rapport d’exercice ou de réponse récente.', 'e1000000-0000-4000-8000-000000000007'),
('DSE13', 'Surveillance nationale 24h/24 — La DSE maintient une capacité nationale de réception et de traitement des alertes 24h/24 et 7j/7.', 'Niveau : Minimal — Preuves attendues : Planning de permanence 24h/24 et 7j/7, liste de contacts d’astreinte, journal des alertes reçues hors heures ouvrables et test documenté de disponibilité.', 'e1000000-0000-4000-8000-000000000007'),
('DSE14', 'Coordination surveillance-laboratoire — La DSE coordonne le circuit national de prélèvement, transport, analyse et communication des résultats avec les laboratoires de référence.', 'Niveau : Minimal — Preuves attendues : SOP du circuit laboratoire, liste des laboratoires et contacts, formulaires de prélèvement, bordereaux de transport, suivi des échantillons et preuve de restitution des résultats.', 'e1000000-0000-4000-8000-000000000007'),
('DSE15', 'Gestion des retards diagnostiques — La DSE identifie, documente et suit les retards de diagnostic afin d''améliorer la performance du réseau national de laboratoires.', 'Niveau : Minimal — Preuves attendues : Registre comportant les dates et heures clés, tableau de bord des délais, calculs d’indicateurs, analyse des écarts et plan d’amélioration suivi dans le temps.', 'e1000000-0000-4000-8000-000000000007'),
('DSE16', 'Coordination nationale du contact tracing — La DSE supervise la consolidation nationale des données de contacts et leur suivi lors des alertes suspectes, probables ou confirmées.', 'Niveau : Minimal — Preuves attendues : Base consolidée ou listes de contacts, procédures et outils de suivi, rapports quotidiens de complétude, chaîne de transmission et compte rendu de coordination entre niveaux.', 'e1000000-0000-4000-8000-000000000007'),
('DSE17', 'Exploitation des signaux sociaux — La DSE analyse les rumeurs, préoccupations communautaires et feedbacks RCCE afin d’orienter les stratégies nationales de communication et de surveillance.', 'Niveau : Minimal — Preuves attendues : Messages ou bulletins de feedback, comptes rendus de réunions, liste de diffusion et exemples d’actions correctrices prises à la suite du retour reçu.', 'e1000000-0000-4000-8000-000000000007'),
('DSE18', 'Coordination des partenaires de surveillance — La DSE maintient une cartographie actualisée des partenaires, ressources et capacités disponibles pour soutenir la surveillance et la réponse.', 'Niveau : Minimal — Preuves attendues : Matrice actualisée des partenaires, zones, piliers, ressources et capacités, coordonnées des points focaux, comptes rendus de coordination et suivi des engagements.', 'e1000000-0000-4000-8000-000000000007'),
('DSE19', 'Pilotage national par les indicateurs — La DSE utilise et diffuse régulièrement les indicateurs nationaux de surveillance afin d’assurer le pilotage stratégique et la cohérence interprovinciale.', 'Niveau : Minimal — Preuves attendues : Tableau validé des indicateurs avec définitions, rapports ou bulletins périodiques, preuve de transmission et compte rendu montrant leur utilisation pour le pilotage.', 'e1000000-0000-4000-8000-000000000007'),
('DSE20', 'Connaissance rapide de la situation nationale — La DSE est capable de produire en moins de 30 minutes une synthèse nationale d’une alerte majeure incluant situation épidémiologique, risques, actions en cours, besoins et recommandations.', 'Niveau : Minimal — Preuves attendues : Modèle de SITREP ou briefing, chronologie d’une alerte, synthèse produite en moins de 30 minutes lors d’un test ou événement, horodatage et liste de diffusion.', 'e1000000-0000-4000-8000-000000000007')
ON DUPLICATE KEY UPDATE
    lib = VALUES(lib),
    description = VALUES(description),
    pilier_id = VALUES(pilier_id),
    is_deleted = FALSE,
    updated_at = utc_timestamp();

COMMIT;

